export type MalayalamKeyDefinition = {
    normal: string;
    shift?: string;
};

export type KeyboardKey = {
    code: string;
    label: string;
    normal?: string;
    shift?: string;
    width?: "wide" | "space";
    tone?: "accent" | "mint";
};

export const malayalamKeyMap: Record<string, MalayalamKeyDefinition> = {
    Digit1: { normal: "ഒ", shift: "ഓ" },
    Digit2: { normal: "അം", shift: "അഃ" },
    Digit3: { normal: "ർ", shift: "ൽ" },
    Digit4: { normal: "ൾ", shift: "ൺ" },
    Digit5: { normal: "ൻ", shift: "ക്ഷ" },
    Digit6: { normal: "ത്ര", shift: "ജ്ഞ" },
    Digit7: { normal: "(", shift: ")" },
    Digit8: { normal: "-", shift: "_" },
    Digit9: { normal: "/", shift: "?" },
    Digit0: { normal: ".", shift: ":" },
    KeyQ: { normal: "ൗ", shift: "ഔ" },
    KeyW: { normal: "ൈ", shift: "ഐ" },
    KeyE: { normal: "ാ", shift: "ആ" },
    KeyR: { normal: "ീ", shift: "ഈ" },
    KeyT: { normal: "ൂ", shift: "ഊ" },
    KeyY: { normal: "ബ", shift: "ഭ" },
    KeyU: { normal: "ഹ", shift: "ങ" },
    KeyI: { normal: "ഗ", shift: "ഘ" },
    KeyO: { normal: "ദ", shift: "ധ" },
    KeyP: { normal: "ജ", shift: "ഝ" },
    BracketLeft: { normal: "ഡ", shift: "ഢ" },
    BracketRight: { normal: "ഞ", shift: "ഞ്" },
    KeyA: { normal: "ോ", shift: "ഓ" },
    KeyS: { normal: "േ", shift: "ഏ" },
    KeyD: { normal: "്", shift: "അ" },
    KeyF: { normal: "ി", shift: "ഇ" },
    KeyG: { normal: "ു", shift: "ഉ" },
    KeyH: { normal: "പ", shift: "ഫ" },
    KeyJ: { normal: "ര", shift: "റ" },
    KeyK: { normal: "ക", shift: "ഖ" },
    KeyL: { normal: "ത", shift: "ഥ" },
    Semicolon: { normal: "ച", shift: "ഛ" },
    Quote: { normal: "ട", shift: "ഠ" },
    KeyZ: { normal: "െ", shift: "എ" },
    KeyX: { normal: "ം", shift: "ഃ" },
    KeyC: { normal: "മ", shift: "ണ" },
    KeyV: { normal: "ന", shift: "ൻ" },
    KeyB: { normal: "വ", shift: "ഴ" },
    KeyN: { normal: "ല", shift: "ള" },
    KeyM: { normal: "സ", shift: "ശ" },
    Comma: { normal: "യ", shift: "ഷ" },
    Period: { normal: "ഷ", shift: "ശ" },
    Slash: { normal: "ഹ", shift: "ഋ" },
    Space: { normal: " " },
};

export const keyboardRows: KeyboardKey[][] = [
    [
        { code: "Escape", label: "esc", tone: "accent" },
        { code: "Digit1", label: "1", normal: "ഒ", shift: "ഓ" },
        { code: "Digit2", label: "2", normal: "അം", shift: "അഃ" },
        { code: "Digit3", label: "3", normal: "ർ", shift: "ൽ" },
        { code: "Digit4", label: "4", normal: "ൾ", shift: "ൺ" },
        { code: "Digit5", label: "5", normal: "ൻ", shift: "ക്ഷ" },
        { code: "Digit6", label: "6", normal: "ത്ര", shift: "ജ്ഞ" },
        { code: "Digit7", label: "7", normal: "(", shift: ")" },
        { code: "Digit8", label: "8", normal: "-", shift: "_" },
        { code: "Digit9", label: "9", normal: "/", shift: "?" },
        { code: "Digit0", label: "0", normal: ".", shift: ":" },
        { code: "Backspace", label: "del", tone: "mint", width: "wide" },
    ],
    [
        { code: "Tab", label: "tab", tone: "mint", width: "wide" },
        { code: "KeyQ", label: "Q", normal: "ൗ", shift: "ഔ" },
        { code: "KeyW", label: "W", normal: "ൈ", shift: "ഐ" },
        { code: "KeyE", label: "E", normal: "ാ", shift: "ആ" },
        { code: "KeyR", label: "R", normal: "ീ", shift: "ഈ" },
        { code: "KeyT", label: "T", normal: "ൂ", shift: "ഊ" },
        { code: "KeyY", label: "Y", normal: "ബ", shift: "ഭ" },
        { code: "KeyU", label: "U", normal: "ഹ", shift: "ങ" },
        { code: "KeyI", label: "I", normal: "ഗ", shift: "ഘ" },
        { code: "KeyO", label: "O", normal: "ദ", shift: "ധ" },
        { code: "KeyP", label: "P", normal: "ജ", shift: "ഝ" },
        { code: "BracketLeft", label: "[", normal: "ഡ", shift: "ഢ" },
    ],
    [
        { code: "CapsLock", label: "caps", tone: "mint", width: "wide" },
        { code: "KeyA", label: "A", normal: "ോ", shift: "ഓ" },
        { code: "KeyS", label: "S", normal: "േ", shift: "ഏ" },
        { code: "KeyD", label: "D", normal: "്", shift: "അ" },
        { code: "KeyF", label: "F", normal: "ി", shift: "ഇ" },
        { code: "KeyG", label: "G", normal: "ു", shift: "ഉ" },
        { code: "KeyH", label: "H", normal: "പ", shift: "ഫ" },
        { code: "KeyJ", label: "J", normal: "ര", shift: "റ" },
        { code: "KeyK", label: "K", normal: "ക", shift: "ഖ" },
        { code: "KeyL", label: "L", normal: "ത", shift: "ഥ" },
        { code: "Semicolon", label: ";", normal: "ച", shift: "ഛ" },
        { code: "Quote", label: "'", normal: "ട", shift: "ഠ" },
    ],
    [
        { code: "ShiftLeft", label: "shift", tone: "mint", width: "wide" },
        { code: "KeyZ", label: "Z", normal: "െ", shift: "എ" },
        { code: "KeyX", label: "X", normal: "ം", shift: "ഃ" },
        { code: "KeyC", label: "C", normal: "മ", shift: "ണ" },
        { code: "KeyV", label: "V", normal: "ന", shift: "ൻ" },
        { code: "KeyB", label: "B", normal: "വ", shift: "ഴ" },
        { code: "KeyN", label: "N", normal: "ല", shift: "ള" },
        { code: "KeyM", label: "M", normal: "സ", shift: "ശ" },
        { code: "Comma", label: ",", normal: "യ", shift: "ഷ" },
        { code: "Period", label: ".", normal: "ഷ", shift: "ശ" },
        { code: "Slash", label: "/", normal: "ഹ", shift: "ഋ" },
        { code: "ShiftRight", label: "shift", tone: "mint", width: "wide" },
    ],
    [
        { code: "ControlLeft", label: "ctrl", tone: "mint" },
        { code: "AltLeft", label: "opt", tone: "mint" },
        { code: "MetaLeft", label: "cmd", tone: "mint" },
        { code: "Space", label: "space", width: "space" },
        { code: "MetaRight", label: "cmd", tone: "mint" },
        { code: "AltRight", label: "alt", tone: "mint" },
        { code: "ControlRight", label: "ctrl", tone: "mint" },
    ],
];

export const keyboardReferenceGroups = [
    {
        title: "സ്വരങ്ങൾ",
        items: [
            "അ",
            "ആ",
            "ഇ",
            "ഈ",
            "ഉ",
            "ഊ",
            "എ",
            "ഏ",
            "ഐ",
            "ഒ",
            "ഓ",
            "അം",
            "അഃ",
        ],
    },
    {
        title: "ചിഹ്നങ്ങൾ",
        items: ["ാ", "ി", "ീ", "ു", "ൂ", "െ", "േ", "ൈ", "ോ", "ൗ", "്", "ം", "ഃ"],
    },
    {
        title: "വ്യഞ്ജനങ്ങൾ",
        items: [
            "ക",
            "ഖ",
            "ഗ",
            "ഘ",
            "ങ",
            "ച",
            "ഛ",
            "ജ",
            "ഝ",
            "ട",
            "ഠ",
            "ഡ",
            "ഢ",
            "ണ",
            "ത",
            "ഥ",
            "ദ",
            "ധ",
            "ന",
            "പ",
            "ഫ",
            "ബ",
            "ഭ",
            "മ",
            "യ",
            "ര",
            "റ",
            "ല",
            "ള",
            "വ",
            "ശ",
            "ഷ",
            "സ",
            "ഹ",
            "ഴ",
        ],
    },
];
